name: Java CI with Maven

on:
  push:
    branches: [ US002-CriarController ]
  pull_request:
    branches: [ US002-CriarController ]
jobs:
 setup-postgresql-ubuntu:
  if: true # false to skip job during debug
  name: Setup PostgreSQL on Ubuntu
  runs-on: ubuntu-latest
  steps:
  - name: Start PostgreSQL on Ubuntu
    run: |
      sudo systemctl start postgresql.service
      pg_isready  
  - name: Create root user
    run: |
      sudo -u postgres psql --command="CREATE USER root PASSWORD 'root'"
  - name: Create timetable database
    run: |
      sudo -u postgres createdb --owner=root coracoes_da_lila
      PGPASSWORD=root psql --username=root --host=localhost --list coracoes_da_lila
   
 
